# base image
FROM nginx:alpine

# copy files required for the app to run
COPY homepage.html /usr/app/nginx/html
COPY login.html /usr/app/nginx/html
COPY person.html /usr/app/nginx/html
COPY student.html /usr/app/nginx/html
COPY student.html /usr/app/nginx/html
COPY style/labone.css /usr/app/nginx/css
