# base image
FROM nginx:alpine

# copy files required for the app to run
COPY homepage.html /usr/share/nginx/html/homepage.html
COPY login.html /usr/share/nginx/html/login.html
COPY person.html /usr/share/nginx/html/person.html
COPY student.html /usr/share/nginx/html/student.html
COPY style/labone.css /usr/share/nginx/css
